### ISSUE TITLE
v1 tag is not pointing to the most recent v1 release

### ISSUE THREAD

**Issue by dcalderonmc** [neondatabase/reset-branch-action#11]
## Steps to reproduce
Use v1 tag on a GitHub Workflow
```yml
 - uses: neondatabase/reset-branch-action@v1
    id: reset-branch
    with:
      project_id: ${{ secrets.NEON_PROJECT_ID }}
      parent: true
...
```

## Expected result
With the `v1` tag is expected to point to the latest `v1` version which in this case right now it's `v1.3.1`

## Actual result
The `v1` tag is pointing to an old version that has a serious bug (solved in https://github.com/neondatabase/reset-branch-action/pull/9) which is `v1.3.0`
