### ISSUE TITLE
Cannot use action with multiple databases

### ISSUE THREAD

**Issue by anthonyma94** [neondatabase/reset-branch-action#12]
I have multiple databases in the main branch. When I run this action, this error pops up:
`ERROR: Multiple databases found for the branch, please provide one with the --database-name option: db_a, db_b`.

Running neonctl manually does not result in this error.

**Comment by shree675** [comment]
Even I am facing this issue. But after going through the [source code](https://github.com/neondatabase/neonctl/blob/main/src/commands/connection_string.ts), it looks like we cannot reset multiple databases with the parent in a single operation, although [these docs](https://neon.tech/docs/guides/reset-from-parent) say that we can reset all databases.

This github action is using `neonctl branches reset` vs `neon branches reset` present in the docs.

In my case, I have two databases but I only need to sync one of them in the child branches. Based on the above source code and the [workflow docs](https://neon.tech/docs/guides/branching-github-actions#reset-from-parent-action), I resolved this issue by specifying the db name in `cs_database` input parameter in the reset-branch workflow step.

If the use case of syncing both the databases arises for me, for now I will probably run another reset-branch workflow step that will reset the second database after the first one.

@duskpoet could you please help clarify or resolve this issue?

**Comment by anthonyma94** [comment]
Just for clarity, `neonctl` can indeed reset all databases. I manually install it in my workflow and use `neonctl branches reset testing/testing --project-id ${{ vars.NEON_PROJECT_ID }} --api-key ${{ secrets.NEON_API_KEY }} --parent` and have had no issues so far with multiple databases.

As to your point of providing a db name, where do you provide it? I couldn't find a suitable key for it.

**Comment by shree675** [comment]
After checking this once again, I seem to have misunderstood the code. The code in [actions.yml](https://github.com/neondatabase/reset-branch-action/blob/main/action.yml) is doing two things:
1. Runs `neonctl reset` command and resets the branch with the parent branch (which resets all the databases in the child branch) - this step actually succeeds.
2. Runs `neonctl cs` command to populate the workflow outputs like db connection string, host, password, etc.. This is the step that fails and returns the above error message that both of us are facing.

Step 1 actually succeeds. I checked just now, all databases in my child branch were indeed reset correctly even though the workflow fails with this error message in step 2. It only fails in step 2 because it needs to populate the db connection string, for which it needs a database name. There is only one db connection string output (`db_url`), hence it needs a single db name to provide the connection string. Even if we don't want to use the output, we need to provide a specific db name.

> As to your point of providing a db name, where do you provide it? I couldn't find a suitable key for it.

This db name is provided in the input field called `cs_database`. You can check this in the docs I linked in the previous message.

I would suggest you to try it out, all dbs are reset correctly even though the workflow step fails with the above error.

**Comment by atilafassina** [comment]
Hey @anthonyma94 and @shree675 .
I can confirm the behavior mentioned here:

> 1. Runs `neonctl reset` command and resets the branch with the parent branch (which resets all the databases in the child branch) - this step actually succeeds.
> 2. Runs `neonctl cs` command to populate the workflow outputs like db connection string, host, password, etc.. This is the step that fails and returns the above error message that both of us are facing.

As @shree675 pointed out, when the action successfully runs, it retrieves the connection string. If the CLI finds multiple databases, it will fail.  

You should be able to pass the database name in the inputs when configuring the action. for example:

```yaml

jobs:
  reset_branch:
    runs-on: ubuntu-latest
    steps:
      # Use the action
      - name: Reset Neon Branch
        uses: neondatabase/reset-branch-action@main
        with:
          project_id: "your-project-id"                     # project ID
          branch: "your-branch-name"                    # branch name or ID to reset
          api_key: ${{ secrets.NEON_API_KEY }}    # Neon API key from GitHub Secrets

          cs_database: "your-database-name"       # Specify a database name
```

That being said, I'm curious what were you expecting to be the default behavior if no db name is passed? In your case, which db were you expecting and based on what?
