### ISSUE TITLE
Supplying default connection string in output; should return connection string of just-reset branch (branch_id missing)

### ISSUE THREAD

**Issue by danielrose7** [neondatabase/reset-branch-action#13]
## Steps to reproduce

```yml
jobs:
name: QA DB Migrations
- runs-on: ubuntu-24.04
- name: Reset Neon Branch
        id: reset_neon_branch
        uses: neondatabase/reset-branch-action@v1
        with:
          api_key: ${{ secrets.NEON_API_KEY }}
          branch: prd-qa
          cs_prisma: true
          cs_role_name: neondb_owner
          parent: true
          project_id: ${{ vars.NEON_PROJECT_ID }}
```

## Expected result
Output connection string for branch that was just reset

## Actual result
Output connection string for our default database URL rather than the one that was just reset

## Environment
Running github action on ubuntu-24.04

## Logs, links

Output from reset

```json
{
  "id": "just-reset-branch-id",
  "parent_id": "parent-id-branch",
  "name": "just-reset-branch-name",
   //...
}
```

I think the action's script is failing to identify a branch_id and is failing back to the default as if you run
`neonctl cs --role-name neondb_owner --prisma` (notice no branch ID as first arg after 'cs') it returns our default db url rather than the one that was just reset

My guess is that jq, a util for interacting with json data, isn't available or there is a formatting issue with the output getting piped to jq (totally a guess).

Think could be explicitly installed with this: https://github.com/marketplace/actions/install-jq though this link says is installed by default

I think would be practical to use the branch name from the input rather than parse from the output
